
#include <cfg_type.h>
#include <../../bogata/include/cfg_gpio_bogata_alpha.h>

const U32 io_pad_bogata_alpha[NUMBER_OF_GPIO_MODULE][32] = {
	/* GPIO group A */
	{
	PAD_GPIOA00_BOGATA_ALPHA, PAD_GPIOA01_BOGATA_ALPHA, PAD_GPIOA02_BOGATA_ALPHA, PAD_GPIOA03_BOGATA_ALPHA,
	PAD_GPIOA04_BOGATA_ALPHA, PAD_GPIOA05_BOGATA_ALPHA, PAD_GPIOA06_BOGATA_ALPHA, PAD_GPIOA07_BOGATA_ALPHA,
	PAD_GPIOA08_BOGATA_ALPHA, PAD_GPIOA09_BOGATA_ALPHA, PAD_GPIOA10_BOGATA_ALPHA, PAD_GPIOA11_BOGATA_ALPHA,
	PAD_GPIOA12_BOGATA_ALPHA, PAD_GPIOA13_BOGATA_ALPHA, PAD_GPIOA14_BOGATA_ALPHA, PAD_GPIOA15_BOGATA_ALPHA,
	PAD_GPIOA16_BOGATA_ALPHA, PAD_GPIOA17_BOGATA_ALPHA, PAD_GPIOA18_BOGATA_ALPHA, PAD_GPIOA19_BOGATA_ALPHA,
	PAD_GPIOA20_BOGATA_ALPHA, PAD_GPIOA21_BOGATA_ALPHA, PAD_GPIOA22_BOGATA_ALPHA, PAD_GPIOA23_BOGATA_ALPHA,
	PAD_GPIOA24_BOGATA_ALPHA, PAD_GPIOA25_BOGATA_ALPHA, PAD_GPIOA26_BOGATA_ALPHA, PAD_GPIOA27_BOGATA_ALPHA,
	PAD_GPIOA28_BOGATA_ALPHA, PAD_GPIOA29_BOGATA_ALPHA, PAD_GPIOA30_BOGATA_ALPHA, PAD_GPIOA31_BOGATA_ALPHA,
	},
	/* GPIO group B */
	{
	PAD_GPIOB00_BOGATA_ALPHA, PAD_GPIOB01_BOGATA_ALPHA, PAD_GPIOB02_BOGATA_ALPHA, PAD_GPIOB03_BOGATA_ALPHA,
	PAD_GPIOB04_BOGATA_ALPHA, PAD_GPIOB05_BOGATA_ALPHA, PAD_GPIOB06_BOGATA_ALPHA, PAD_GPIOB07_BOGATA_ALPHA,
	PAD_GPIOB08_BOGATA_ALPHA, PAD_GPIOB09_BOGATA_ALPHA, PAD_GPIOB10_BOGATA_ALPHA, PAD_GPIOB11_BOGATA_ALPHA,
	PAD_GPIOB12_BOGATA_ALPHA, PAD_GPIOB13_BOGATA_ALPHA, PAD_GPIOB14_BOGATA_ALPHA, PAD_GPIOB15_BOGATA_ALPHA,
	PAD_GPIOB16_BOGATA_ALPHA, PAD_GPIOB17_BOGATA_ALPHA, PAD_GPIOB18_BOGATA_ALPHA, PAD_GPIOB19_BOGATA_ALPHA,
	PAD_GPIOB20_BOGATA_ALPHA, PAD_GPIOB21_BOGATA_ALPHA, PAD_GPIOB22_BOGATA_ALPHA, PAD_GPIOB23_BOGATA_ALPHA,
	PAD_GPIOB24_BOGATA_ALPHA, PAD_GPIOB25_BOGATA_ALPHA, PAD_GPIOB26_BOGATA_ALPHA, PAD_GPIOB27_BOGATA_ALPHA,
	PAD_GPIOB28_BOGATA_ALPHA, PAD_GPIOB29_BOGATA_ALPHA, PAD_GPIOB30_BOGATA_ALPHA, PAD_GPIOB31_BOGATA_ALPHA,
	},
	/* GPIO group C */
	{
	PAD_GPIOC00_BOGATA_ALPHA, PAD_GPIOC01_BOGATA_ALPHA, PAD_GPIOC02_BOGATA_ALPHA, PAD_GPIOC03_BOGATA_ALPHA,
	PAD_GPIOC04_BOGATA_ALPHA, PAD_GPIOC05_BOGATA_ALPHA, PAD_GPIOC06_BOGATA_ALPHA, PAD_GPIOC07_BOGATA_ALPHA,
	PAD_GPIOC08_BOGATA_ALPHA, PAD_GPIOC09_BOGATA_ALPHA, PAD_GPIOC10_BOGATA_ALPHA, PAD_GPIOC11_BOGATA_ALPHA,
	PAD_GPIOC12_BOGATA_ALPHA, PAD_GPIOC13_BOGATA_ALPHA, PAD_GPIOC14_BOGATA_ALPHA, PAD_GPIOC15_BOGATA_ALPHA,
	PAD_GPIOC16_BOGATA_ALPHA, PAD_GPIOC17_BOGATA_ALPHA, PAD_GPIOC18_BOGATA_ALPHA, PAD_GPIOC19_BOGATA_ALPHA,
	PAD_GPIOC20_BOGATA_ALPHA, PAD_GPIOC21_BOGATA_ALPHA, PAD_GPIOC22_BOGATA_ALPHA, PAD_GPIOC23_BOGATA_ALPHA,
	PAD_GPIOC24_BOGATA_ALPHA, PAD_GPIOC25_BOGATA_ALPHA, PAD_GPIOC26_BOGATA_ALPHA, PAD_GPIOC27_BOGATA_ALPHA,
	PAD_GPIOC28_BOGATA_ALPHA, PAD_GPIOC29_BOGATA_ALPHA, PAD_GPIOC30_BOGATA_ALPHA, PAD_GPIOC31_BOGATA_ALPHA,
	},
	/* GPIO group D */
	{
	PAD_GPIOD00_BOGATA_ALPHA, PAD_GPIOD01_BOGATA_ALPHA, PAD_GPIOD02_BOGATA_ALPHA, PAD_GPIOD03_BOGATA_ALPHA,
	PAD_GPIOD04_BOGATA_ALPHA, PAD_GPIOD05_BOGATA_ALPHA, PAD_GPIOD06_BOGATA_ALPHA, PAD_GPIOD07_BOGATA_ALPHA,
	PAD_GPIOD08_BOGATA_ALPHA, PAD_GPIOD09_BOGATA_ALPHA, PAD_GPIOD10_BOGATA_ALPHA, PAD_GPIOD11_BOGATA_ALPHA,
	PAD_GPIOD12_BOGATA_ALPHA, PAD_GPIOD13_BOGATA_ALPHA, PAD_GPIOD14_BOGATA_ALPHA, PAD_GPIOD15_BOGATA_ALPHA,
	PAD_GPIOD16_BOGATA_ALPHA, PAD_GPIOD17_BOGATA_ALPHA, PAD_GPIOD18_BOGATA_ALPHA, PAD_GPIOD19_BOGATA_ALPHA,
	PAD_GPIOD20_BOGATA_ALPHA, PAD_GPIOD21_BOGATA_ALPHA, PAD_GPIOD22_BOGATA_ALPHA, PAD_GPIOD23_BOGATA_ALPHA,
	PAD_GPIOD24_BOGATA_ALPHA, PAD_GPIOD25_BOGATA_ALPHA, PAD_GPIOD26_BOGATA_ALPHA, PAD_GPIOD27_BOGATA_ALPHA,
	PAD_GPIOD28_BOGATA_ALPHA, PAD_GPIOD29_BOGATA_ALPHA, PAD_GPIOD30_BOGATA_ALPHA, PAD_GPIOD31_BOGATA_ALPHA,
	},
	/* GPIO group E */
	{
	PAD_GPIOE00_BOGATA_ALPHA, PAD_GPIOE01_BOGATA_ALPHA, PAD_GPIOE02_BOGATA_ALPHA, PAD_GPIOE03_BOGATA_ALPHA,
	PAD_GPIOE04_BOGATA_ALPHA, PAD_GPIOE05_BOGATA_ALPHA, PAD_GPIOE06_BOGATA_ALPHA, PAD_GPIOE07_BOGATA_ALPHA,
	PAD_GPIOE08_BOGATA_ALPHA, PAD_GPIOE09_BOGATA_ALPHA, PAD_GPIOE10_BOGATA_ALPHA, PAD_GPIOE11_BOGATA_ALPHA,
	PAD_GPIOE12_BOGATA_ALPHA, PAD_GPIOE13_BOGATA_ALPHA, PAD_GPIOE14_BOGATA_ALPHA, PAD_GPIOE15_BOGATA_ALPHA,
	PAD_GPIOE16_BOGATA_ALPHA, PAD_GPIOE17_BOGATA_ALPHA, PAD_GPIOE18_BOGATA_ALPHA, PAD_GPIOE19_BOGATA_ALPHA,
	PAD_GPIOE20_BOGATA_ALPHA, PAD_GPIOE21_BOGATA_ALPHA, PAD_GPIOE22_BOGATA_ALPHA, PAD_GPIOE23_BOGATA_ALPHA,
	PAD_GPIOE24_BOGATA_ALPHA, PAD_GPIOE25_BOGATA_ALPHA, PAD_GPIOE26_BOGATA_ALPHA, PAD_GPIOE27_BOGATA_ALPHA,
	PAD_GPIOE28_BOGATA_ALPHA, PAD_GPIOE29_BOGATA_ALPHA, PAD_GPIOE30_BOGATA_ALPHA, PAD_GPIOE31_BOGATA_ALPHA,
	},
};

const U32 alv_pad_bogata_alpha[ALVPADS] = 
{
	PAD_GPIOALV00_BOGATA_ALPHA, PAD_GPIOALV01_BOGATA_ALPHA, 
	PAD_GPIOALV02_BOGATA_ALPHA, PAD_GPIOALV03_BOGATA_ALPHA,
	PAD_GPIOALV04_BOGATA_ALPHA, PAD_GPIOALV05_BOGATA_ALPHA
	};

const U32 bus_pad_bogata_alpha[6] = {
	PAD_BUS_STATIC_CNTL_BOGATA_ALPHA, PAD_BUS_STATIC_ADDR_BOGATA_ALPHA, PAD_BUS_STATIC_DATA_BOGATA_ALPHA,
	PAD_BUS_VSYNC_BOGATA_ALPHA, PAD_BUS_HSYNC_BOGATA_ALPHA, PAD_BUS_DE_BOGATA_ALPHA
};
